# Gravity of environment for fabric simulation
gravity_x: 0.0 # m/s^2
gravity_y: 0.0 # m/s^2
gravity_z: -9.81 # m/s^2

dt: 0.003 # seconds. Simulated time per iteration of the fabric simulatiob.
set_sim_rate_auto: false  # to set the simulation rate and dt automaticall, do not use
num_substeps: 3 # Number of substeps per iteration based on 2019 Small Steps XPBD paper.
num_steps: 1 # experimental only. do not change from 1

fabric_x: 2.0 # fabric x size in meters
fabric_y: 2.0 # fabric y size in meters
fabric_density: 1.0 # fabric mass per meter square (kg/m^2)
fabric_resolution: 25 # particle resolution per meter 

fabric_stretching_compliance: 1.0e-9  # 0.0
fabric_bending_compliance: 1.0e-5 # Note, fabric stretching compliance assumed to be 0.0 already.

initial_height: 0.8 # initial fabric height from ground (m)

num_hang_corners: 0 # num of corners to hang dlo from (options: 0,1,2,3,4)

# Global artificial velocity damping coefficients. Defaults to 0.0. 
global_damp_coeff_v: 7.1e-1 # 2.1e-4; // 0.9e-3

simulation_rate: 1000.0
rendering_rate: 100.0 # Hz, frequency to publish the fabric vertices and edges to RVIZ visualization markers

wrench_pub_rate: 100.0 # Hz, frequency to publish the fabric forces at the attachment points

fabric_points_topic_name: "cloth_points" # topic name to publish the RVIZ visualization marker msgs
fabric_points_frame_id: "map" # the reference tf frame ID that the visualization marker msgs are published in.

# Odometry topics that publishes robot positions to the fabric simulator
odom_01_topic_name: "d1/ground_truth/fabric_mount/odom"
odom_02_topic_name: "d2/ground_truth/fabric_mount/odom"
odom_03_topic_name: "d3/ground_truth/fabric_mount/odom"
odom_04_topic_name: "d4/ground_truth/fabric_mount/odom"

# TF frame names that the fabric is assumed to be attached.
wrench_01_frame_id: "d1_tf_fabric_mount_link"
wrench_02_frame_id: "d2_tf_fabric_mount_link"
wrench_03_frame_id: "d3_tf_fabric_mount_link"
wrench_04_frame_id: "d4_tf_fabric_mount_link"

fabric_rob_z_offset_: 0.0 # z offset between the specified frame and fabric attachement

# Published topic names of the forces of attached robots.
wrench_01_topic_name: "d1/fabric_wrench_stamped"
wrench_02_topic_name: "d2/fabric_wrench_stamped"
wrench_03_topic_name: "d3/fabric_wrench_stamped"
wrench_04_topic_name: "d4/fabric_wrench_stamped"

